# Generated by Django 5.0.6 on 2024-10-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modulereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_number', models.IntegerField()),
                ('Module_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_title', models.CharField(max_length=50)),
                ('notefile', models.FileField(upload_to='documents/')),
                ('moduleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='N_Module_id', to='myclassroomapp.modulereg')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='N_User_id', to='myclassroomapp.userreg')),
            ],
        ),
        migrations.AddField(
            model_name='modulereg',
            name='Userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M_User_id', to='myclassroomapp.userreg'),
        ),
    ]
